---
title: 'CONSORT-Herbal 2026: CONSORT Herbal 2026 Statement: updated guideline for reporting randomised trials of medicinal plant extracts and natural products as active ingredients and finished products.'
date-registered: 10 November 2025
year-registered: 2025
date-updated: null
contact-name: Dr Banaz Jalil
contact-email: b.jalil@ucl.ac.uk
categories:
- Clinical Trials
---

Clinical research on medicinal plant extracts and natural products (including herbal medicines) and bioactive natural products differs from work with single compounds. Extracts from plants, fungi, or animals are complex mixtures containing active, partially active, and inactive components, often affecting multiple targets. Their composition can change based on preparation methods and source materials, making it challenging to report and interpret the pharmacological, toxicological and clinical findings in a reproducible and transparent way. The quality, safety, and efficacy of such products are highly product-specific. Therefore, the medicinal plant extracts and natural products used in a clinical intervention must be clearly defined to ensure that clinical outcomes can be accurately linked to the specific product tested.

The initial CONSORT Extension for Herbal Interventions was published in 2006, providing a solid basis for the reporting of the intervention used in publication of clinical trials. However, an assessment by the non-profit organisation Empoweredbyevidence.org in collaboration with Monash University, Melbourne, Australia of scientific literature on herbal medicine as Curcuma longa, Sylibum marianum and Echinacea found a limited and partly or entirely lacking adaptation of the CONSORT herbal extension 2006 in published clinical trials, thereby limiting the possibility of replication, interpreting and translating these into practice. Therefore, almost 20 years after the intial CONSORT extention for Herbal Medicine Interventions, this project aims to provide an updated CONSORT statement with the ambitions of improving research conduct, report and practice in the field as well as via the involvement of different stakeholders, the team aims to promote better implementation of and covering all natural complex ingredients with a medical claim in the updated CONSORT statement across the sector over the next 5 years.

{{< include ../_template.qmd >}}
