---
title: CheRIHoSS - Checklist of Reporting Items for Horizon Scanning Studies
date-registered: 23 May 2025
year-registered: 2025
date-updated: null
contact-name: Sonia Garcia Gonzalez-Moral
contact-email: Sonia.garcia-gonzalez-moral@newcastle.ac.uk
categories:
- Other
---

Horizon scanning is a method used to systematically detect signs of future developments. In health and care is it used to inform decisions about new and emergining innovative health and care technologies before these technologies become available and evidence is generated. The use of horizon scanning in health and care decision-making is gaining traction. Current applications of horizon scanning in the health and care context include: predicting the impact of new technologies on health and care services, regulatory frameworks or policies; identifying future developments, gaps, trends or business opportunities; and helping with adoption and diffusion of new technologies. Furthermore, horizon scanning is already established as a crucial step in the health technology assessment (HTA) process as a method to detect innovative technologies and issue early alerts to HTA bodies ahead of these technologies being placed on the market. There are other multiple uses and applications of horizon scanning methods in the healthcare context. This variability and broad application warrant the need for transparent and robust methods reporting. Currently there is an absence of guidelines for reporting the methods used in these studies. A lack of clear standardised terminology also means that study methods are often unclear.This guideline aims to fill the methodological gap identified by providing a checklist and a glossary of terms that horizon scanning practitioners, researchers, peer-reviewers and journal editors can work with to improve quality and consistency of horizon scanning studies.This guideline and checklist is the result of years of practice in the field of horizon scanning in health and care.

Website: [https://osf.io/m39vw/](https://osf.io/m39vw/)

{{< include ../_template.qmd >}}
