project:
  type: website
  preview:
    watch-inputs: true

website:
  site-url: 'https://equator-network.github.io/equator-website/'
  image: "assets/logos/equator_logo.png"
  favicon: "assets/favicons/equator-network-16x16.png"
  search: false 
  bread-crumbs: false
  navbar:
    background: light
    logo: "assets/logos/equator_logo.png"
    logo-alt: EQUATOR Network Home Page
    right:
      - href: training.qmd
        text: Training
      - text: About
        menu: 
          - text: The UK EQUATOR Centre
            href: about/uk-equator-centre.qmd
          - text: The EQUATOR Network
            href: about/equator-network.qmd
          - text: International EQUATOR Centres
            href: about/international-equator-centres.qmd
          - text: About reporting guidelines
            href: about/reporting-guidelines.qmd
          - text: Contact
            href: about/contact.qmd
      - href: reporting-guidelines/index.qmd
        icon: search
  page-footer:
    left: |
      Created by the
      [UK EQUATOR Centre](https://www.equator-network.org/about-us/uk-equator-centre/)
    center:
      - text: "Terms of Use"
        href: terms-of-use.qmd
      - text: "Privacy Policy"
        href: privacy-policy.qmd
        # #TODO license?
    right:
      - icon: twitter
        href: https://twitter.com/equatornetwork
        aria-label: Quarto Twitter
      - icon: github
        aria-label: EQUATOR GitHub
        href: github
  page-navigation: true
  open-graph: true

format:
  html:
    theme: cosmo
    css: /assets/css/main.css
    toc: true
    title-block-banner: true
    title-block-banner-color: white





