project:
  type: website
  preview: 
    watch-inputs: true

website:
  title: "equator-website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right: 
      - href: reporting-guidelines/index.qmd
        icon: search
  search: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true




