project:
  type: website
  preview:
    watch-inputs: true

website:
  title: "equator-website"
  navbar:
    left:
      - text: Reporting Guidelines
        menu:
          - href: reporting-guidelines/index.qmd
            text: Search all
          - href: reporting-guidelines/under-development/index.qmd
            text: Under development
      - about.qmd
    right: 
      - href: reporting-guidelines/index.qmd
        icon: search
  search: false
  open-graph: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true




