# More resources on developing a reporting guideline

The EQUATOR team [published guidance on developing a reporting
guideline](http://journals.plos.org/plosmedicine/article?id=10.1371/journal.pmed.1000217)
in 2010. It draws on the team’s extensive experience in the development of
reporting guidelines and offers practical guidance to scientists
considering developing new guidelines or extending and updating existing
guidance. The guidance also draws on [the results of a survey of reporting
guideline developers](https://www.ncbi.nlm.nih.gov/pubmed/18578566)
conducted by the EQUATOR team in 2008 and [an early description of the
process of developing a reporting
guideline](https://www.ncbi.nlm.nih.gov/pubmed/16464421), published in
Spanish in 2005.

The [GREET reporting
guideline](https://www.equator-network.org/reporting-guidelines/greet/)
development team used the EQUATOR guidance when developing their guideline.
Their [protocol published in *BMC Medical
Education*](https://bmcmededuc.biomedcentral.com/articles/10.1186/1472-6920-13-9)
is a good example of a robust plan for a reporting guideline.

We recommend publishing an Explanation and Elaboration document alongside
your reporting guideline. This E&E document describes each item in your
checklist, why it is important, and gives examples of good reporting. The
[CONSORT](https://pubmed.ncbi.nlm.nih.gov/40228832/) and
[STROBE](https://www.ncbi.nlm.nih.gov/pubmed/17941714) E&E documents are
good examples.

The SQUIRE guideline was [first published in
2005](https://www.ncbi.nlm.nih.gov/pubmed/16195563), [updated in
2008](https://www.ncbi.nlm.nih.gov/pubmed/18836063), and [updated again in
2015](https://www.ncbi.nlm.nih.gov/pubmed/26369893). The development plan
included these periodic updates. Read more about the development of the
SQUIRE Statement at [their dedicated
website](http://www.squire-statement.org/).

The CONSORT guideline was [first published in
1996](https://pubmed.ncbi.nlm.nih.gov/8773637/), [updated in
2001](https://pubmed.ncbi.nlm.nih.gov/11304106/), [updated in
2010](https://pubmed.ncbi.nlm.nih.gov/20332509/), [and updated more
recently in 2025](/reporting-guidelines/consort/index.qmd). Read more about
the development of the CONSORT Statement at [their dedicated
website](http://www.consort-statement.org/about-consort/history).

The [CONSORT extension for trials assessing nonpharmacologic treatments
(PMID: 18283201)](https://www.ncbi.nlm.nih.gov/pubmed/18283201) provides a
good example of the difference between a new guideline and an extension of
an existing guideline, and how to develop and publish an extension.
