# Writing up and publishing your reporting guideline

## Write the reporting guideline

We suggest publishing the guideline in a short (~2,000 words) paper detailing the need for a new guideline, the development process, and introducing the reporting guidance statement and/or checklist.

Short, unambiguous reporting item statements should be written based on the reporting item consensus decisions taken at the meeting, ordered to logically follow a paper’s structure.

Consider what [data sharing elements](https://www.bmj.com/content/386/bmj-2024-079694) need to be provided when creating or updating a reporting guideline.

As it would be impractical for the full guideline development group to actively work on the guideline wording and publication, we suggest setting up a writing team on behalf of the group. However, all members of the group should sign off on the final text.

## Pilot the reporting guideline

During the writing revision process, consider piloting your reporting guideline with non-expert users. Developers have had success trialling their guidelines with student groups. Leave time in the revision process to make changes to language based on what you find in the pilot. 

## Write the Explanation and Elaboration document

Alongside the short guideline publication, we suggest writing an Explanation and Elaboration document (~10,000 words) explaining why each reporting item is important and giving examples of good reporting for every item. Again, a writing team should produce this document and all members of the wider development team should approve it.

We suggest publishing the two documents simultaneously, to enhance the usability of the guideline.

## Publish the reporting guideline

Your guideline is a tool that will be used and built upon after it is published. It could be considered for translation, adaptation, or extension to apply to more specific conditions, or the wording of the recommendations could be cut or shortened. Journals can recommend its use, and authors can download and use the guideline checklist during the writing and submission process.

How you choose to publish and disseminate your guideline should support all of these possible uses. Consider the following:

- Published reporting guidelines need to be easily accessible to their users. We strongly encourage publishing as an open-access article or in an open-access journal that allows the checklist to be freely used. If you choose to publish behind a paywall, we strongly encourage you to arrange with the journal beforehand that at least the checklist is provided in an open-access and free-to-use manner.

- Some journals have created special sections for publishing guidelines and methods papers. Examples include [PLoS Medicine](http://collections.plos.org/reporting-guidelines) and the [BMJ](http://www.bmj.com/content/337/bmj.a2201.full?maxtoshow=&HITS=10&hits=10&RESULTFORMAT=&fulltext=groves+guidelines&searchid=1&FIRSTINDEX=0&resourcetype=HWCIT).

- The EQUATOR Network regularly searches the literature for new reporting guidelines. However, we encourage authors to [inform us](mailto:shona.kirtley@csm.ox.ac.uk) when their guideline is published so that we can include it in our database and support its wider uptake.

- Many key reporting guidelines are published simultaneously in a number of journals, such as was done for the [CONSORT](https://www.equator-network.org/reporting-guidelines/consort/) and [STROBE](https://www.equator-network.org/reporting-guidelines/strobe/) Statements.

- You can include an explicit copyright and fair use statement on your reporting guideline papers and your website. Examples of guideline groups’ policies include the [SPIRIT Statement](http://www.spirit-statement.org/copyright/) and the [STROBE Statement](https://www.strobe-statement.org/index.php?id=strobe-aims).

- Useful websites when considering copyright:
 - [UK Copyright Service](http://www.copyrightservice.co.uk)
 - [US Copyright Office](http://www.copyright.gov/)
 - [Creative Commons](http://creativecommons.org/)