---
title: Standards of Reporting the Network Pharmacology of Chinese Medicine
date-registered: 01 April 2026
year-registered: 2026
date-updated: null
contact-name: Lin Haixiong
contact-email: lhxiong@foxmail.com
categories:
- Other
---

Since 2010, the concepts and methods of network pharmacology have been applied in traditional Chinese medicine research, and they have played a significant role in identifying potential herbal therapies during the COVID-19 pandemic. In 2021, Li Shao developed the “Guidelines for Network Pharmacology Evaluation Methods”. However, due to the fact that this guideline focuses on methodological assessment and lacks detailed research report standards, methodological suggestions, and validation methods, it cannot effectively guide the reporting of network pharmacology research. Therefore, many reports on network pharmacology still rely on STROBE statements, CONSORT statements, and the 2017 CONSORT-CHM format statements as references for research design and reporting. However, these lists are mainly designed for reporting observational studies or clinical randomized controlled trials, and thus are not applicable to the analysis of traditional Chinese medicine network pharmacology. This has hindered the high-quality development of traditional Chinese medicine. This study referred to the relevant content of the “Guidelines for Network Pharmacology Evaluation Methods”, reviewed relevant literature in domestic and foreign databases, and combined with traditional Chinese medicine theory and the core concept of “syndrome”, summarized and integrated the key points of reporting in traditional Chinese medicine network pharmacology, thereby promoting high-quality reporting in this field.

{{< include ../_template.qmd >}}
