---
editor:
  markdown:
    wrap: none
---

+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [STROBE](reporting-guidelines/strobe)                                                                                                                                             | **Observational Epidemiology**, including:                                                                                                                                                                                    |
|                                                                                                                                                                                   |                                                                                                                                                                                                                               |
|                                                                                                                                                                                   | -   Cohort studies (e.g., longitudinal, prospective, and retrospective studies)                                                                                                                                               |
|                                                                                                                                                                                   | -   Case-control studies (e.g., case-referent studies)                                                                                                                                                                        |
|                                                                                                                                                                                   | -   Cross-sectional studies (e.g., transverse and prevalence studies)                                                                                                                                                         |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| <br>                                                                                                                                                                              | **Systematic reviews**                                                                                                                                                                                                        |
|                                                                                                                                                                                   |                                                                                                                                                                                                                               |
| [PRISMA](reporting-guidelines/prisma)                                                                                                                                             | Systematic reviews of trials                                                                                                                                                                                                  |
|                                                                                                                                                                                   |                                                                                                                                                                                                                               |
| <br>                                                                                                                                                                              | <br>                                                                                                                                                                                                                          |
|                                                                                                                                                                                   |                                                                                                                                                                                                                               |
| [PRISMA-P](reporting-guidelines/prisma-protocols/)                                                                                                                                | Systematic review protocols                                                                                                                                                                                                   |
|                                                                                                                                                                                   |                                                                                                                                                                                                                               |
| <br>                                                                                                                                                                              | <br>                                                                                                                                                                                                                          |
|                                                                                                                                                                                   |                                                                                                                                                                                                                               |
| [MOOSE](reporting-guidelines/meta-analysis-of-observational-studies-in-epidemiology-a-proposal-for-reporting-meta-analysis-of-observational-studies-in-epidemiology-moose-group/) | Meta-analyses of Observational studies                                                                                                                                                                                        |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| <br>                                                                                                                                                                              | **Randomized trials**                                                                                                                                                                                                         |
|                                                                                                                                                                                   |                                                                                                                                                                                                                               |
| [CONSORT](reporting-guidelines/consort)                                                                                                                                           | Randomized trials (clinical trials, or experimental studies of health interventions)                                                                                                                                          |
|                                                                                                                                                                                   |                                                                                                                                                                                                                               |
| <br>                                                                                                                                                                              | <br>                                                                                                                                                                                                                          |
|                                                                                                                                                                                   |                                                                                                                                                                                                                               |
| [SPIRIT](reporting-guidelines/spirit-2013-statement-defining-standard-protocol-items-for-clinical-trials/)                                                                        | Protocols for randomized trials                                                                                                                                                                                               |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [SRQR](reporting-guidelines/srqr)                                                                                                                                                 | Qualitative Research                                                                                                                                                                                                          |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [CARE](reporting-guidelines/care)                                                                                                                                                 | Case Reports                                                                                                                                                                                                                  |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [STARD](reporting-guidelines/stard)                                                                                                                                               | Diagnostic Test Accuracy Studies                                                                                                                                                                                              |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [TRIPOD+AI](reporting-guidelines/tripod-statement/)                                                                                                                               | Prediction Models                                                                                                                                                                                                             |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [ARRIVE](reporting-guidelines/improving-bioscience-research-reporting-the-arrive-guidelines-for-reporting-animal-research/)                                                       | Animal Research                                                                                                                                                                                                               |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [SQUIRE](reporting-guidelines/squire)                                                                                                                                             | Quality Improvement in Healthcare                                                                                                                                                                                             |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [CHEERS](reporting-guidelines/cheers/)                                                                                                                                            | Economic Evaluations                                                                                                                                                                                                          |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: {tbl-colwidths="\[25,75\]"}