---
title: 'PRISTINE: Preferred Reporting Items for Syntheses Through Interactive, Navigable Evidence-portals'
date-registered: 18 June 2025
year-registered: 2025
date-updated: null
contact-name: Tomasz Kozakiewicz, Newcastle University
contact-email: t.kozakiewicz2@newcastle.ac.uk
categories:
- Literature reviews
---

The promise of large language models to not only screen and extract data from studies (Gartlehner et al., 2024) but also summarise them (Ovelman et al., 2024) makes one-stop shop websites for answering decision-makers’ questions closer than ever before, yet no formal guidance exists for creators of such websites.

Evidence portals are websites that provide reliable web-based summaries of research findings, offering accessible insights without the need to consult individual studies (Gough and White, 2018). If successful, they can serve as a go-to knowledge platform for policymakers and other decision-makers, including frontline professionals (nurses, teachers, etc), seeking clarity on what is likely to work, when, how, for whom and at what cost. A prominent example is the Teaching and Learning Toolkit developed by the Education Endowment Foundation, with most school leaders in England who report using it to make decisions (Higgins et al., 2022).

Due to the intensive nature of knowledge translation required (e.g. the necessity to create meticulous evidence standards that underpin them), few of them exist at scale and are kept up to date, but that will soon change. Recently, significant resources were committed to the development of infrastructure to create living evidence synthesis (Behavioural Insights Team, 2024; Wellcome Trust, 2024). To increase evidence synthesis findings uptake for busy policymakers and practitioners, the recently formed Evidence Synthesis Infrastructure Collaborative recommends that information previously contained in text-based PDF reports be reported using interactive, web-based interfaces. While guidance for visual and interactive maps is already in progress (PRISMA-Evidence Gap Map extension), no formal guidance exists for evidence portals. I coordinated the web development for the International Initiative for Impact Evaluation’s Development Evidence Portal. Based on that experience, I believe this emerging field would benefit from building on the work of Gough and White (2018), who provided early recommendations for portal creators based on an analysis of 14 English-language portals. Their recommendations are limited to evidence of effectiveness. Using the theoretical framework of research uptake developed by Higgins et al (2022) their focus seems to be on accuracy (internal and external validity) and to a lesser degree also applicability and actionability. They do not provide much guidance on the remaining dimensions of research use that may be sacrificed with too much focus on accuracy. These competing dimensions that I suggest focusing on are accessibility, appropriateness and acceptability. These dimensions would be explored using the following research questions:

- How to make portals reporting relevant for a broader range of study designs? 
- Which information is key to present in the portal’s web-based elements, how to make it easily accessible? 
- How to report equity considerations and involvement of stakeholders (particularly patients and the public)? 
- How to use web-based, interactive features to increase the portal’s usefulness, actionability and to whom?

{{< include ../_template.qmd >}}
