# EQUATOR Network: what we do and how we are organised

The EQUATOR Network is an “umbrella” organisation that brings together researchers, medical journal editors, peer reviewers, developers of reporting guidelines, research funding bodies and other collaborators with mutual interest in improving the quality of research publications and of research itself.

We are developing into a global initiative covering all areas of health research and all nations, and actively involving all key stakeholders. We have launched the first five national centres that will substantially contribute to expanding EQUATOR activities: the [UK EQUATOR Centre](https://www.equator-network.org/about-us/uk-equator-centre/) (also the EQUATOR Network’s head office), [French EQUATOR Centre](https://www.equator-network.org/about-us/french-equator-centre/), [Canadian EQUATOR Centre](https://www.equator-network.org/about-us/canadian-equator-centre/), [Australasian EQUATOR Centre](https://www.equator-network.org/about-us/australasian-equator-centre/),  [Chinese EQUATOR Centre](https://www.equator-network.org/about-us/chinese-equator-centre/) and [US EQUATOR Centre](https://www.equator-network.org/about-us/usa-equator-centre/). The new centres will focus on national activities aimed at raising awareness and supporting adoption of good research reporting practices. They will work with partner organisations and initiatives and will also contribute to the work of the EQUATOR Network as a whole.

**EQUATOR’s mission and goals**

The EQUATOR mission is to achieve accurate, complete, and transparent reporting of all health research studies to support research reproducibility and usefulness. Our work increases the value of health research and helps to minimise avoidable waste of financial and human investments in health research projects.

To achieve its mission the EQUATOR Network has the following major goals:

- Maintain and further develop a comprehensive collection of online resources providing up-to-date information, tools and other materials related to health research reporting ([Library for health research reporting](https://www.equator-network.org/library/))
- Actively promote the use of reporting guidelines and good research reporting practices through an education and [training](https://www.equator-network.org/category/events/) programme
- Assist in the [development](http://journals.plos.org/plosmedicine/article?id=10.1371/journal.pmed.1000217), dissemination and implementation of robust reporting guidelines
- Support journals, universities and other organisations in [implementing reporting guidelines](https://www.equator-network.org/toolkits/) through development of tools, strategies, education and other activities
- Undertake [research projects](https://www.equator-network.org/about-us/) enhancing the value of health-related research
- Set up a global network of local [EQUATOR centres](https://www.equator-network.org/about-us/) to facilitate the improvement of health research reporting on a worldwide scale

Aside from its core activities of providing focused resources and training, EQUATOR is committed to research on current research and its publication to enhance the value of health-related research. Research topics include reviews of time trends in the nature and quality of publications; the development of tools and strategies to improve the planning, design, conduct/management and reporting of biomedical research; and investigating strategies to help journals to improve the quality of manuscripts.

The EQUATOR Network is directed by an international Executive Group that brings together leading experts in health research methodology, statistics, reporting and editorial work.

**Executive Group members:**

- [**Gary Collins**](https://www.equator-network.org/about-us/equator-network-what-we-do-and-how-we-are-organised/#Gary), 125th Anniversary Chair, Professor of Medical Statistics, Department of Applied Health Sciences, University of Birmingham, UK; Director, UK EQUATOR Centre, and current chair of the EQUATOR Network. Email: [g.s.collins@bham.ac.uk](mailto:g.s.collins@bham.ac.uk)
- [**David Moher**](https://www.equator-network.org/about-us/equator-network-what-we-do-and-how-we-are-organised/#David), Senior Scientist, Ottawa Health Research Institute, Ottawa, Canada; Director, Canadian EQUATOR Centre, and former chair of the EQUATOR Network.
- [**Philippe Ravaud**](https://www.equator-network.org/about-us/equator-network-what-we-do-and-how-we-are-organised/#Philippe), Director, Centre of Epidemiology at the Hotel-Dieu (Paris); Director, French EQUATOR Centre
- **[Tammy Hoffmann](https://www.equator-network.org/about-us/equator-network-what-we-do-and-how-we-are-organised/#Tammy)**, Professor of Clinical Epidemiology, Institute for Evidence-Based Healthcare, Bond University, Australia
- [**Zhaoxiang Bian**](https://www.equator-network.org/about-us/equator-network-what-we-do-and-how-we-are-organised/#Zhaoxiang), Chair Professor in the School of Chinese Medicine and Tsang Shiu Tim Endowed Professor of Chinese Medicine Clinical Studies, Hong Kong Baptist University

**Advisory Group members**:

- [**Ana Marušić**](https://www.equator-network.org/about-us/equator-network-what-we-do-and-how-we-are-organised/#Ana), Professor and Chair, Department of Research in Biomedicine and Health, University of Split, Croatia

**Former Executive Group members:**

- **Doug Altman**, former Professor of Statistics in Medicine, Centre for Statistics in Medicine, University of Oxford, UK; Director, UK EQUATOR Centre
- **Iveta Simera**, formerly Senior Operations & Development Manager at The Global Health Network (TGHN), Centre for Tropical Medicine & Global Health, University of Oxford, UK

**Former Advisory Group members**

- **John Hoey**, Associate Professor (adjunct), University of Toronto, Toronto, Canada
- **Kenneth F. Schulz**, Distinguished Scientist and Vice President, Quantitative Sciences, Family Health International, Chapel Hill, USA
- **Trish Groves**, formerly Head of Research, BMJ & Editor-in-chief, BMJ Open

**Biographies**

**Gary Collins**

Professor Gary Collins is a 125th Anniversary Chair, and Professor of Medical Statistics at the [University of Birmingham,](https://research.birmingham.ac.uk/en/persons/gary-collins) UK, and Director of the UK EQUATOR Centre. He previously worked at the University of Oxford for 19 years, where he was the Director of the Centre for Statistics in Medicine. Gary has been involved in the development of numerous reporting guidelines, including [GATHER](https://www.equator-network.org/2016/08/03/guidelines-for-accurate-and-transparent-health-estimates-reporting-the-gather-statement/), [CONSORT-AI](https://www.equator-network.org/reporting-guidelines/consort-artificial-intelligence/), [CONSORT-Surrogate](https://www.equator-network.org/reporting-guidelines/consort-surrogate/), [DECIDE-AI](https://www.equator-network.org/reporting-guidelines/reporting-guideline-for-the-early-stage-clinical-evaluation-of-decision-support-systems-driven-by-artificial-intelligence-decide-ai/), and led the development of the TRIPOD and [TRIPOD+AI](https://www.equator-network.org/reporting-guidelines/tripod-statement/) reporting guidelines for clinical prediction models. More recently he was involved in the 2025 updates of the [CONSORT](https://www.equator-network.org/reporting-guidelines/consort/) and [SPIRIT](https://www.equator-network.org/reporting-guidelines/spirit-2013-statement-defining-standard-protocol-items-for-clinical-trials/) statements.

**Ana Marušić**

Dr Ana Marušić is Professor of Anatomy and Chair of the Department of Research in Biomedicine and Health at the University of Split School of Medicine, Split, Croatia. She is also co-editor in chief of the _Croatian Medical Journal_, a member journal of the International Committee of Medical Journal Editors (ICMJE). She took part in developing statements on mandatory registration of clinical trials and uniform form for declaring conflict of interest. She has been the President of the World Association of Medical Editors (WAME), President of the Council of Science Editors (CSE), and Council member of the European Association of Science Editors (EASE).

Ana has published more than 150 articles in peer reviewed journals. Her primary research interest is focused on the interactions between the immune and bone systems, but also on peer review and medical educational. Apart from teaching anatomy, she teaches university students the principles of research methodology and scientific communication in a mandatory undergraduate course. She is the co-author of a textbook _Principles of Research in Medicine_ (first edition in 1996), now published both in Croatian and English. She is an active member of the Croatian branch of the Cochrane Collaboration, Chair of the Board of the Croatian Institute of Global Health, and creator of the first Croatian public registry of clinical trials.

**David Moher**

Dr David Moher is a senior scientist with the Ottawa Health Research Institute. He is also Associate Professor, Department of Epidemiology & Community Medicine, Faculty of Medicine, University of Ottawa, and holds a University of Ottawa Research Chair. In May 2014 he became Director of the Canadian EQUATOR Centre.

David has published more than 150 papers, including approximately 40 systematic reviews and more than 50 articles on the methodology of conducting and reporting clinical trials and systematic reviews. He is Director of the University of Ottawa’s Evidence-based Practice Center, convenor of the Cochrane Collaboration’s Bias Methods Group, and an editorial board member of several journals. He helped develop many reporting guidelines, including the CONSORT, QUOROM / PRISMA, MOOSE, and STARD Statements.

**Philippe Ravaud**

Professor Philippe Ravaud is Director of the Centre of Epidemiology at the Hotel-Dieu (Paris), Director of the French Cochrane Centre, Director of the INSERM Research Team “Methods of therapeutic evaluation of chronic diseases”, and a senior lecturer at Paris Descartes University and Columbia University (Mailman School of Public Health). In May 2014 he became Director of the French EQUATOR Centre.

Philippe received his MD from Pierre and Marie Curie University, Paris and completed a residence in rheumatology in the Assistance Publique-Hopitaux de Paris network. In parallel, he received an MSc in Epidemiology and a PhD in Clinical Epidemiology at the University of Nancy (France). For over 15 years his primary research has been evaluating and developing methodological solutions to assess treatments in patients with chronic diseases. The methods used are multiple (e.g., methodological systematic reviews, simulations, analytical methods, development of sham trials). His recent research has addressed evaluating non-pharmacological treatments; developing and validating endpoints; meta-analyses and network meta-analyses; and interpreting and communicating research results. His publication record includes more than 280 peer-reviewed papers, including 28 in the “big 6″ medical journals; he is the first or last author for more than 110 articles.

**Tammy Hoffmann**

Professor Tammy Hoffmann is a Professor of Clinical Epidemiology at the Institute for Evidence-Based Healthcare, Bond University. Her research spans many aspects of evidence-based practice, shared decision making, knowledge translation, and minimising waste in research. Tammy has been involved in the development of a number of reporting guidelines. As part of her interest in improving the reporting, useability, and uptake of effective non-pharmacological interventions, she led the development of the TIDieR (Template for Intervention Description and Replication) checklist and guide. She has over 300 publications, including many in the world’s leading medical journals. She is also the lead author of a widely used interdisciplinary evidence-based practice book (Evidence-Based Practice across the Health Professions, 4th ed 2023).

**Zhaoxiang Bian**

Professor Bian obtained his Bachelor Degree of Chinese Medicine from the Nanjiang University of Chinese Medicine in 1988, Master Degree of Chinese Medicine from Beijing University of Chinese Medicine in 1991, and PhD degree in Integrative Chinese and Western Medicine from Guangzhou University of Chinese Medicine in 1994. Currently, he is Chair Professor in the School of Chinese Medicine and Tsang Shiu Tim Endowed Professor of Chinese Medicine Clinical Studies, Hong Kong Baptist University (HKBU), and also serves as associate Vice-President (Chinese Medicine Development) of HKBU, Director of Clinical Division, School of Chinese Medicine, Director of Hong Kong Chinese Medicine Clinical Study Centre and Director of Chinese EQUATOR Centre. Dr Bian’s major research interests are: (1) Clinical research methodology and reporting guidelines; (2) Clinical and translational study of gastrointestinal diseases; (3) Chinese medicine wisdom-driven new drug discovery and development. His academic achievements include 400+ academic publications, 80+ US & China patents, and one new drug clinical trial licence from China National Medical Product Administration.

**EQUATOR Milestones**

Since its launch in 2008, the programme has already achieved important milestones:

- Developed a free online [Library for health research reporting](https://www.equator-network.org/library/)
- In collaboration with the Pan American Health Organization (PAHO/WHO) launched a Spanish section in the EQUATOR website and signed a three year memorandum on mutual collaboration in promoting responsible research reporting in the Americas, especially in Latin America and the Caribbean regions
- Built international recognition and reputation as the leading authority and resource portal in the area of health research reporting. Reference to EQUATOR is included in the “[Recommendations for the Conduct, Reporting, Editing, and Publication of Scholarly Work in Medical Journals](http://www.icmje.org/)” (formerly Uniform Requirements for Biomedical Manuscripts), the most fundamental guidelines developed by the International Committee of Medical Journal Editors that are followed by most biomedical journals
- Organised workshops, seminars, talks and Annual Lectures on issues relevant to research reporting (see our [past events](https://www.equator-network.org/category/events/all-past-events/))
- Together with the German Cochrane Centre organised the 1st EQUATOR Scientific Symposium: [ACT now: Accuracy, Completeness and Transparency in health research reporting](https://www.equator-network.org/2012/10/10/act-now-accuracy-completeness-and-transparency-in-health-research-reporting/), Freiburg, October 2012
- Completed several research projects and published a number of [research papers and articles promoting good research reporting](https://www.equator-network.org/about-us/uk-equator-centre/equator-publications/)
- Published a regular [online newsletter](https://www.equator-network.org/category/news/newsletter-only/) and set up a [LinkedIn group](http://www.linkedin.com/groups/EQUATOR-Network-Improving-reporting-health-5032663) disseminating information about new reporting guidelines and the latest developments

**Principles**

The work of EQUATOR increases the **usability of available research evidence**. Our work supports the work of organisations such as the Cochrane Collaboration in the development of systematic reviews and NICE in the development of clinical practice guidelines. EQUATOR also helps research funders maximise the utility of new information arising from the research they fund.

Complete, accurate and transparent reporting is an **integral part of responsible research conduct**. Reporting guidelines are important tools for achieving high standards in reporting health studies. In order to reach their potential, reporting guidelines need to be used widely and routinely by researchers/authors, editors and peer reviewers. This effort needs to be strongly supported by research funders and regulatory bodies.

EQUATOR is a **long-term programme of research support** and **improvement** and not a closed fixed term project. Ongoing EQUATOR activities are expected to increase the usability and value of published research both in clinical practice and to aid further research, thus ensuring that maximum value is gained from financial investment in health research.
