---
title: STROBE-Vision - an extension of the STROBE statement
date-registered: 23 February 2021
year-registered: 2021
date-updated: null
contact-name: Dr Tasanee Braithwaite, School of Life course, Sciences and School of Immunology and Microbial Sciences, Kings College London, UK; and The Medical Eye Unit, Guy’s and St Thomas’ NHS Foundation Trust, London.
contact-email: tasaneebraithwaite@gmail.com
categories:
- Observational studies
---

This reporting guideline aims to adopt and extend the STROBE (STrengthening the Reporting of OBservational studies in Epidemiology) reporting guideline focusing on observational studies on human vision. Specifically, the reporting guideline under development aims to encourage the comprehensive reporting of surveys on population-based vision impairment prevalence, outlining the risks of bias concerning this type of study and recommending reporting items on prevalence estimates and meta-analyses, to permit their proper assessment. The need for a reporting guideline was made clear from the last WHO World Report on Vision (2019), the Lancet Global Health Commission on Global Eye Health (2021) and the Vision Loss Expert Group and the Global Burden of Disease Study (2021).

Ethics committee approval was obtained for this project from the London School of Hygiene and Tropical Medicine Institutional Review Board (December 2019). A two-round Delphi survey will reach a list of agreed items made from the original STROBE items and additional, vision-related ones. Panellists will include epidemiologists, statisticians, journal editors, Cochrane editors, vision impairment and eye disease subject matter experts, guideline developers, and representatives of non-governmental organisations.

The group plans to publish the reporting guideline as an open-access document in 2021.

{{< include ../_template.qmd >}}
