# How to integrate reporting guidelines in your journal’s workflow

Thank you for exploring the world of reporting guidelines and journals.
Wherever your journal is in the journey to fight research waste, we’re here
to support you with tools and resources. This toolkit will help you:

- Get practical resources to facilitate the incorporation of reporting
  guidelines into your journal
- Get technical solutions to improve the use of reporting guidelines by
  your authors
- Help spread the word about the consequences of bad reporting

Brand new to the idea of reporting guidelines? Read more about the
[**problems in health research
today**](whats-wrong-with-health-reporting-today.qmd) and how it [**affects
all stakeholders**](how-poor-reporting-affects-you.qmd), including
journals.

Unsure about the efficacy of reporting guidelines and how they fit into
journals? Read about some [**common myths and misconceptions about
reporting guidelines, and evidence for why they
work**](reporting-guidelines-and-journals-fact-fiction.qmd) and [**hear
from some
journals**](case-studies-how-journals-implement-reporting-guidelines.qmd)
successfully using reporting guidelines today.

Excited about reporting guidelines and ready for the next step? Read about
[**formulating an implementation plan with your
journal**](creating-your-journals-reporting-guideline-policy.qmd) and the
[**four kinds of implementation plans we offer tools
for**](four-possible-implementation-routes.qmd).

Implementation plan ready? Here’s some suggestions for [**introducing your
authors, peer reviewers, and readers to the new
policy**](launch-and-promote-your-journals-reporting-guideline-policy.qmd).

Time to implement reporting guidelines at your journal? We’ve got [**tools
and
templates**](tools-and-templates-for-implementing-reporting-guidelines.qmd)
for you to incorporate into your workflow.

We hope you find the contents of this toolkit helpful. If you have any
questions or concerns, please get in touch with the EQUATOR Network team by
[email](mailto:g.s.collins@bham.ac.uk), on
[Twitter](https://twitter.com/EQUATORNetwork), or on
[LinkedIn](https://www.linkedin.com/groups/5032663/). We welcome any extra
tools or case studies that you would like to contribute from your journal!

### 
