# What’s wrong with health reporting today?

## “Reporting research is as important a part of a study as its design or analysis”

The Declaration of Helsinki states that researchers, editors and publishers
have ethical obligations when the results of research are published. It
stresses the completeness and accuracy of the reporting of human research.
However, the evidence shows that we are far from this ideal:

**Delayed publication**

- Whole studies are not either reported or are reported long after research
  is completed

**Studies are incompletely reported**

- Crucial components are left out: who the study participants were, what
  interventions were used, etc.
- Data and results are selectively reported; outcomes are left out

**Studies are inaccurately reported**

- Inconsistencies between abstracts and main text
- Statistical errors
- Harms are inadequately reported
- Data and graphs are confusing or misleading
- ‘Spin’: misinterpretation of results

The result is unusable information. These studies cannot be reproduced,
properly appraised, or contribute to a systematic review’s dataset. The
information gathered never enters the body of evidence; it is as if the
research was never done. The funding involved is wasted and the
contributions of the participants are squandered. With no record of the
study, future researchers may unknowingly repeat the work.

The research is thus rendered useless, fallen victim to bad reporting.

## Reporting guidelines: the solution to poor reporting

Reporting guidelines are checklists designed by methodologists and
researchers. They describe the minimum set of items needed to ensure a
study is reported accurately and completely, so that its results can be
used. Although over 300 guidelines designed for specific study types now
exist, researchers have been slow to use them. We at the EQUATOR Network
believe that every stakeholder in the research publication process can play
a role in promoting the effective use of reporting guidelines.

[This short
article](https://www.csescienceeditor.org/article/the-equator-network-supporting-editors-in-publishing-well-reported-health-research/)
in *Science Editor* explains a bit more about how reporting guidelines can
support the work that journal editors do.

- [Read more here](how-poor-reporting-affects-you.qmd) if you’re uncertain
  about how bad reporting affects journals
- [Read more here](creating-your-journals-reporting-guideline-policy.qmd)
  if you want to start implementing reporting guidelines in your journal
- [Go back](index.qmd) to the toolkit homepage
