---
title: 'Reporting Guidelines for Organoid-Based Clinical Trials: An Extension of the CONSORT Statement'
date-registered: 18 June 2025
year-registered: 2025
date-updated: null
contact-name: Yuting Duan; LinShi
contact-email: 18702009530@163.com; shilin@gzhmu.edu.cn
categories:
- Clinical Trials
---

Organoids are stem cell- or tissue-derived three-dimensional structures that recapitulate the key pathological features and genetic background of their tissue of origin. They offer a physiologically relevant model for simulating human organ development, function, and disease progression, while overcoming limitations inherent to animal models, such as species-specific differences in metabolism and immune responses. Their spatial architecture and cellular fidelity enable real-time observation of disease dynamics, and when combined with gene-editing technologies, organoids facilitate rapid validation of gene functions or therapeutic targets, significantly enhancing experimental reproducibility. Moreover, organoid models align with the "3Rs" principle---Replacement, Reduction, and Refinement---by reducing the reliance on animal models for drug toxicity testing and lowering associated research and development costs. Food and Drug Administration (FDA) and pharmaceutical research institutions recommend organoid research as an effective alternative to animal experiments.

The increasing number of organoid-related clinical trials in recent years further underscores the need of establishing clinical guidelines. As interest in organoid research continues to grow, so does the need for standardized reporting guidelines. However, no dedicated reporting framework currently exists for organoid-based clinical trials, increasing the risk of incomplete reporting and the prevalence of spin. For example, clinical trials involving organoids typically require reporting on the organoid's composition, source, and the gene editing techniques used. But, the CONSORT guidelines do not include items addressing this information.

Therefore, the project leads advocate for the development of a reporting guideline specific to organoid clinical trials. Such a guideline would not only improve the quality and transparency of organoid research reporting but also facilitate the translation of basic science into clinical applications, ultimately accelerating the advancement of personalized medicine and interdisciplinary innovation.

{{< include ../_template.qmd >}}
