---
title: PRISMA-EGMs - PRISMA-Evidence and Gap Maps
date-registered: 14 September 2023
year-registered: 2023
date-updated: null
contact-name: Fiona Campbell, University of Newcastle, Campbell Collaboration
contact-email: Fiona.Campbell1@newcastle.ac.uk
categories:
- Literature reviews
---

According to the developers of this reporting guideline, evidence and gap maps (EGM) are  an approach used in evidence synthesis, and aim to describe the body of evidence in contrast to a synthesis of evidence addressing a specific topic. EGMs differ from mapping and scoping reviews, requiring an a priori development of a coding matrix, and resulting in visual and interactive maps. The developers state that the existing guidance (PRISMA-Scr) “does not cover the unique features of EGMs and it therefore warrants a separate guideline.” 

The group is developing a scoping review on the methods used in EGMs. They plan to conduct a Delphi survey including review methodologists and experts in evidence gaps in the panel. They plan to publish the reporting guideline until 2025, as an open access document, and they have funding from Newcastle University for the development.

{{< include ../_template.qmd >}}
