---
title: WATER - Guideline for Wastewater Analysis and Tracking in Epidemiological Reporting
date-registered: 23 May 2025
year-registered: 2025
date-updated: null
contact-name: Yoshitaka Nishikawa
contact-email: nishikawa.yoshitaka.4x@kyoto-u.ac.jp
categories:
- Other
---

Wastewater and Environmental Surveillance (WES) serves as an important tool for monitoring environmental and community health by analyzing wastewater. Historically, WES has been used to detect chemicals, illegal drugs, pathogenic microorganisms, and drug-resistant bacteria. Particularly during the COVID-19 pandemic, the demand for WES research became evident.Currently, due to the multidisciplinary nature of WES, the absence of specific guidance has resulted in varied approaches and data reporting across studies, making comparisons and broader analysis challenging. Unlike existing frameworks for observational research, WES involves unique aspects such as diverse data sources, complex detection methods, and specific data usage requirements, which need special attention.This guideline aims to provide a set of straightforward reporting standards for WES studies, covering essential areas like study design, sample collection, data analysis, ethical considerations, and interpretation of results. By following these standards, researchers can improve the quality and transparency of their work, facilitating better understanding and collaboration in public health efforts.

{{< include ../_template.qmd >}}
