---
title: 'APT-SAP: Enhancing the design, conduct and analysis of Adaptive and Platform Trials through consensus-driven Statistical Analysis Plan guidance'
date-registered: 17 June 2025
year-registered: 2025
date-updated: null
contact-name: Munya Dimairo
contact-email: m.dimairo@sheffield.ac.uk
categories:
- Clinical Trials
---

The increasing need for efficient and innovative trial designs to rapidly evaluate investigative treatments and expedite clinical decision-making for the quick benefit of patients has led to the growing use of Adaptive and Platform Trials (APTs) in a randomised setting. Adaptive designs allow for pre-specified changes to trial design aspects (trial adaptations) based on accrued interim outcome data while maintaining valid conclusions. Examples of trial adaptations include early stopping of ineffective treatment arms, early trial stopping upon gathering sufficient evidence to reach conclusions, or allocating more participants to promising treatment arms. Platform trials further enhance this flexibility by enabling the addition of new treatment arms (or study populations/subpopulations) to an ongoing study, with or without interim analyses.

While APTs offer clear benefits, their inherent flexibility and statistical efficiency introduce considerable operational and statistical complexities across the design, conduct, analysis, and reporting stages. Trial adaptations should be accounted for in all these stages to yield valid, trustworthy, and interpretable results, and to maintain public confidence in the generated evidence. Therefore, timely access to high-quality Statistical Analysis Plans (SAPs) for APTs, addressing both interim and final analyses alongside detailed protocols, is vital for enhancing transparency and facilitating accurate interpretation of results.

However, current SAP guidance does not adequately address the specific considerations posed by APTs in randomised setting. Many publicly available APT-SAPs, including related reports of published results, provide insufficient detail on statistical methods. This makes it difficult to interpret reported results and reproduce methods and findings -- hindering the credibility of reported results. This lack of transparency undermines public trust and contributes to research waste. In addition, there is a notable absence of guidance on the proportionate level of interim information that can be released (e.g., to trial participants, patients, investigators, or the research community at conferences) from ongoing APTs without compromising trial integrity.

{{< include ../_template.qmd >}}
