---
title: 'StaRLiF: Standards for reporting the development and validation of literature search filters'
date-registered: 12 December 2025
year-registered: 2025
date-updated: null
contact-name: Alexander Pachanov, 1. Faculty of Health Sciences Brandenburg, Brandenburg Medical School
contact-email: alexander.pachanov@mhb-fontane.de
categories:
- Literature reviews
---

The way a search strategy is constructed for evidence syntheses (ESs) determines how many records will need to be screened and whether relevant studies might be missed, potentially altering the review’s conclusions. Therefore, a well-designed strategy aims to maximize retrieval of evidence relevant to the review question while avoiding retrieval of irrelevant records. When available, search filters for bibliographic databases can be incorporated into search strategies to help achieve this goal. Search filters are structured combinations of search terms, field tags, and database-specific syntax, developed to identify studies with a specific design (methodological filters) or focused on a particular subject, such as a disease, geographic location or population (topic filters).

The development of a search filter typically involves selecting candidate terms using expert judgment and/or objective methods such as term frequency analysis within a set of relevant records (gold standard), designing the filter, and testing its performance through validation. Documenting these steps with sufficient detail is essential to enable reproducibility, critical appraisal, and to judge whether a filter can be applied to a specific context. However, reviews of search filter studies have shown that these steps are often reported incompletely. Publications frequently lack details on gold standard generation, database interfaces used, calculation of performance metrics, and validation procedures. 
In many disciplines, inconsistencies in the documentation of key methodological details and results are addressed through reporting guidelines (e.g., PRISMA) that offer structured frameworks to promote standardization, transparency, and reproducibility in research. However, no systematically developed guideline exists nor is planned for the reporting of the development and validation of search filters.

The lack of such guidance impacts authors, peer reviewers, editors, researchers and information specialists. Authors of filter studies face uncertainty regarding which methodological details are essential to report, while journal editors and peer reviewers lack concrete criteria to systematically evaluate the completeness and clarity of filter studies submitted for publication. Moreover, insufficient reporting makes it difficult for ES researchers and information specialists - who play a central role in designing and applying search strategies - to assess whether a filter’s performance is generalizable beyond the setting in which it was developed. In addition, insufficient reporting limits future progress, as developers of new filters lack clear examples of sound methodological practices to guide their work. 
To address these issues, our project aims to develop a structured, consensus-based reporting guideline for studies on the design and validation of all types of search filters. This guideline will clearly define the key reporting elements necessary for accurate documentation of study methods and results, and support authors in appropriately addressing the limitations of their filter within the study report. By encouraging consistent and transparent reporting, the guideline aims to support clearer assessments of methodological rigor, assist peer reviewers and editors in their evaluations, and enhance the comparability of search filter studies. Ultimately, this guideline will help ensure that search filters are reported in a way that supports their reliable use in ESs, thereby strengthening the overall quality and credibility of reviews in healthcare and other disciplines.

{{< include ../_template.qmd >}}
