---
title: LEVERAGE - GuideLines for rEporting the deVelopment, dEliveRy and evAluation of health interventions/policies Guided by commonly used systEms approaches
date-registered: 28 February 2025
year-registered: 2025
date-updated: null
contact-name: Bai Li
contact-email: bai.li@bristol.ac.uk
categories:
- Other
---

Internationally, governments and inter-governmental organisations (particularly the WHO) are calling for systems approaches to tackle leading public health challenges such as obesity, food insecurity and health impact of climate change. Although an increasing number of interventions (led by governmental bodies or researchers) reported to have applied a systems approach systematic reviews have identified poor reporting (authors failed to report sufficiently and transparently how systems thinking or methods were used) and there is uncertainty around the exact meaning of “a systems approach”.To address this problem and advance the application and development of systems approaches in public health worldwide, Bai Li and colleagues published practical guiding questions to assist researchers, journal editors, research founders and practitioners to report and review public health interventions underpinned by systems approaches. Although the guiding questions were created based on latest academic knowledge and experiences of the authors who led relevant work in a number of countries, they were not developed through a Delphi study. Building on the published guiding questions, the LEVERAGE Executive Group aim to develop (through a rigorous process, including a Delphi study and an in-person international workshop) a guideline for reporting development, delivery and evaluation of health interventions/policies underpinned by systems approaches.The developers anticipate that the guideline will be applicable to any study design used for the development, delivery/implementation or evaluation/monitoring of health interventions/policies underpinned by one of the three most commonly used systems approaches (i.e. System Dynamics/SD, Agent Based Modeling/ABM, Social Network Analysis/SNA). Items specifically for AI and machine learning studies which are increasingly used in systems science will be included. The group plan to involve leading international organisations (e.g. System Dynamics Society, International Network for Social Network Analysis/INSNA, Open Modeling Foundation), public health journals and international experts in relevant disciplines and fields.

[Read an opinion article](https://www.frontiersin.org/journals/public-health/articles/10.3389/fpubh.2022.892931/full) about the guiding questions

{{< include ../_template.qmd >}}
