---
title: RECONSIDER -- Reporting extension of CONSORT and SPIRIT for Inclusion, Diversity, Ethnicity and Race
date-registered: 18 November 2022
year-registered: 2022
date-updated: null
contact-name: Peter Feldman
contact-email: p.feldman@nari.edu.au
categories:
- Clinical Trials
---

This project to develop an extension of CONSORT and SPIRIT reporting guidelines will focus on the reporting of variables relevant to ethnically, culturally and linguistically diverse participants in randomised controlled trials (RCTs). The resulting guideline will cover both methodological (for example, techniques of recuitment) and reporting aspects (relevant data for ethnically diverse people) of RCTs and will apply to both the main manuscript and supplementary materials.

The leading group plans to review the literature, consult with diverse ethnic communities in Australia, UK and Canada and conduct a Delphi survey. The development of the project, funded by the Commonwealth of Australia (represented by the National Health and Medical Research Council) started in February 2022, and the group plans to publish the guideline as an open-access document.

{{< include ../_template.qmd >}}
