---
title: The reporting for Chinese herbal medicine placebo guidelines in randomized controlled trials
date-registered: 01 April 2026
year-registered: 2026
date-updated: null
contact-name: Xuanlin Li
contact-email: lixuanlinhnzy@163.com
categories:
- Clinical Trials
---

As a crucial component in verifying the efficacy of medications, placebos play an important role in randomized controlled trials of Chinese herbal medicine (CHM). The CONSORT Extension for Chinese Herbal Medicine Formulas 2017: Recommendations, Explanation, and Elaboration, includes five items specifically addressing the reporting of CHM-placebo. However, an epidemiological evaluation conducted by our team on randomized controlled trials of CHM containing CHM-placebo published between January 2018 and September 2025 revealed that compliance with these items was generally low. In particular, there were serious omissions regarding "Name and amount of each ingredient", "Description of the similarity of placebo with the intervention", "Quality control and safety assessment, if any", "Production information: where, when, how, and by whom the placebo was produced". Some studies merely mentioned the CHM-placebo had a similar appearance to CHM without specifying their exact composition, preparation process, or degree of similarity to the test drug in terms of physical properties. Most studies did not report the results of placebo quality control tests, nor did they clarify whether the CHM-placebo's safety had been verified prior to the trial. These missing details directly impacted the trial's safety assessment, transparency, and success rate of blinding.

Compared to fields such as acupuncture and surgery, reporting guidelines for CHM-placebo still have significant room for improvement. For acupuncture, two specific reporting standards---ACURATE and SHARE---have been established. The former specifies reporting requirements from the perspective of operational procedures, while the latter emphasizes the reporting of acupuncture details such as patient positioning, needle insertion angle, and needle equipment information, as well as non-therapeutic contextual factors such as doctor-patient communication and practitioner qualifications. In the field of surgery, the ASPIRE guidelines systematically outline the design principles for sham surgery, including identifying key elements by deconstructing surgical procedures, defining levels of placebo fidelity, and implementing risk-minimization strategies. These guidelines are grounded in the complexity of interventions within their respective fields and emphasize comprehensive reporting throughout the entire process, from design to implementation. In contrast, the production process of CHM-placebos involves multiple stages, including excipient selection, and sensory simulation such as appearance, odor, and taste, making it complex. However, there is currently a lack of targeted, comprehensive reporting standards for CHM-placebo.

This guideline will draw on experience from the aforementioned fields and, based on existing issues, specify the items to be reported and set out specific requirements, covering the entire process of CHM-placebo from production to usage. This guideline aims to enhance the safety, transparency, and blinding success rate of randomized controlled trials of CHM, thereby ensuring the reliability and reproducibility of the trial results. This guideline is intended for researchers, journal editors, and peer reviewers involved in conducting, reviewing, or publishing such studies.

{{< include ../_template.qmd >}}
